sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
addons:
  apt_packages:
  - pandoc
branches:
  only:
  - 0.11
before_script:
- pip install coveralls
script:
- "./build.py -v -X install_dependencies"
- "./build.py -v -X analyze install"
after_success:
- coveralls --verbose
deploy:
  provider: pypi
  user: pybuilder-travis2
  distributions: sdist bdist_wheel
  server: https://upload.pypi.org/legacy/
  on:
    branch: 0.11
    repo: pybuilder/pybuilder
    python: '3.5'
  password:
    secure: R6ZV1e/xWtCLjpbnxEU3JIZ6242HTicV6eo3j6Fc2xMbcR/5Z5Lnh58cMLohwfmvEjTIjHKEPjeHCOw7mTW9ueRe2VoTiLMzP9EDLON4TBmB6OqklPW8mI/oXQjiRZbqOwluAsuP+dFzZ5U4oyUmHZUW4us2XM1azUcfXr3RaJM=
