sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
addons:
    apt_packages: [ pandoc ]
branches:
  only:
  - master
  - doc/sphinxdoc
  - 0.11
before_script:
- pip install coveralls
script:
- "./build.py -v -X install_dependencies analyze install"
after_success:
- coveralls --verbose
deploy:
  provider: pypi
  user: pybuilder-travis2
  distributions: "sdist"
  server: https://upload.pypi.org/legacy/
  on:
    branch: 0.11
    repo: pybuilder/pybuilder
    python: '3.5'
  password:
    secure: D49QJr9Z4v9yz9VObFw0q44o2fy3YBjI48b6+Vb1qr2RNMF5GpVj+xWFTr9j1qMw7ilfwWCEKlHytKmh/OSOStUcd1vTlasGz8YefBCP8iIbvp9M6qcBKqMlp8f/6uxwUxak+OMvj5WuKwtyIUy8L9JwDxd02Q12MUW6SNtu2Lo=
