environment:
  matrix:
  - PYTHON_BIN_HOME: "C:\\Python26"
  - PYTHON_BIN_HOME: "C:\\Python26-x64"
  - PYTHON_BIN_HOME: "C:\\Python27"
  - PYTHON_BIN_HOME: "C:\\Python27-x64"
  - PYTHON_BIN_HOME: "C:\\Python33"
  - PYTHON_BIN_HOME: "C:\\Python33-x64"
  - PYTHON_BIN_HOME: "C:\\Python34"
  - PYTHON_BIN_HOME: "C:\\Python34-x64"
  - PYTHON_BIN_HOME: "C:\\Python35"
  - PYTHON_BIN_HOME: "C:\\Python35-x64"
  - PYTHON_BIN_HOME: "C:\\Python36"
  - PYTHON_BIN_HOME: "C:\\Python36-x64"

# stop as soon as the first failing test
matrix:
  fast_finish: false # disabling until pybuilder is updated for compat with Windows

branches:
  only:
  - master
  - 0.11

shallow_clone: true

clone_depth: 1

build: false

test_script:
  - cmd: "%PYTHON_BIN_HOME%\\Scripts\\pip install virtualenv"
  - cmd: "%PYTHON_BIN_HOME%\\python.exe -m virtualenv venv"
  - ps: .\venv\Scripts\activate.ps1
  - cmd: where python
  - cmd: python --version
  - cmd: pip install -U setuptools~=36.0
  - cmd: python build.py -v -X install_dependencies
  - cmd: python build.py -v -X analyze install
